[package]
name = "rizonet-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Rizonet CLI: scaffold, run and build Rizonet applications."

[[bin]]
name = "rizonet"
path = "src/main.rs"

[dependencies]
clap.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
rizonet-core = { workspace = true, features = ["iconify"] }
